# Generated by Django 3.1.2 on 2020-11-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allowed', 'Allowed'), ('Denied', 'Denied')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Videos', 'Videos'), ('Music', 'Music')], max_length=250, null=True),
        ),
    ]
